version: '3.8'

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    networks:
      - bridge1

  reverse_proxy:
    image: nginx:latest
    ports:
      - "8081:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Nginx configuration file
    networks:
      - bridge1
      - bridge2

  http_server1:
    build:
      context: .
      dockerfile: Dockerfile.http
    volumes:
      - web-data:/usr/local/apache2/htdocs/
    networks:
      - bridge2
      - bridge_db  # Connecté au réseau de la base de données

  http_server2:
    build:
      context: .
      dockerfile: Dockerfile.http
    volumes:
      - web-data:/usr/local/apache2/htdocs/
    networks:
      - bridge2
      - bridge_db  # Connecté au réseau de la base de données

  db:  # Service de base de données
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  # Mot de passe root
      MYSQL_DATABASE: mydatabase  # Nom de la base de données à créer
      MYSQL_USER: user  # Nom d'utilisateur
      MYSQL_PASSWORD: userpassword  # Mot de passe de l'utilisateur
    volumes:
      - db_data:/var/lib/mysql  # Persistance des données
    networks:
      - bridge_db  # Connecté au réseau de la base de données

networks:
  bridge1:
    driver: bridge
  bridge2:
    driver: bridge
  bridge_db:  # Nouveau réseau pour la base de données
    driver: bridge

volumes:
  web-data:
  db_data:  # Volume pour la base de données
